### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by josefmana** [josefmana/pd-dem-cr1t#4]
Prepare a draft of the intro.

**Comment by josefmana** [comment]
Ondrej prepared.

**Comment by OndrejBezdicek** [comment]
Ahoj Josefe, prosím tě, co znamená Ondrej prepared a kde je ten dokument Intro? O.

**Comment by josefmana** [comment]
Ahoj, Intro, které jsi posílal Martě, ona překlopila do Quarta a je teď inkorporováno do .qmd a .pdf dokumentu v tomto depozitáři ve složce /texts.
